version: 2

jobs:
  build:
    working_directory: ~/core.typed
    docker:
      - image: circleci/openjdk:10-jdk
    steps:
      - checkout
      - run:
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
            chmod +x linux-install-1.9.0.397.sh
            sudo ./linux-install-1.9.0.397.sh
      - run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.0"}}}'
