name: Run tests with clj

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11.0-jdk
    steps:
      - name: Download clj
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
          chmod +x linux-install-1.9.0.397.sh
          sudo ./linux-install-1.9.0.397.sh
      - name: Run tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.0"}}}'
