name: Run tests with clj

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Run annotator.jvm tests
        run: ./script/test
        working-directory: module-annotator.jvm
        #- run: mvn --version
        #- run: mvn test
        #- run: mvn install -DskipTests=true
        #- run:
        #    command: |
        #      git clone https://github.com/frenchy64/runtime-type-inference-lein.git ~/runtime-type-inference-lein
        #- run:
        #    command: |
        #      cd ~/runtime-type-inference-lein
        #      ./infer-types.sh
      - name: Run analyzer.jvm tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.10.0"}}}'
        working-directory: module-analyzer.jvm
      - name: Run checker.jvm tests
        run: ./script/test
        working-directory: module-checker.jvm
      - name: Run runtime.jvm tests
        run: ./script/test
        working-directory: module-runtime.jvm
      - name: Run lib.clojure tests
        run: ./script/test
        working-directory: module-lib.clojure
      - name: Run lang.jvm tests
        run: ./script/test
        working-directory: module-lang.jvm
