name: Run tests with clj

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: ['1.10.1', '1.11.0-master-SNAPSHOT']
        jdk: ['1.8', '1.11', '1.13']
        submodule: ['annotator.jvm', 'analyzer.jvm', 'checker.jvm', 'lib.clojure', 'lang.jvm', 'runtime.jvm']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Run ${{ matrix.submodule }} tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version \"${{ matrix.clojure }}\"}}}'
        working-directory: module-${{ matrix.submodule }}
