name: Run tests with clj

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: 
          - 1.10.1
          #- 1.11.0-master-SNAPSHOT
        jdk: 
          - 1.8
          #- 1.11
          - 1.13
        submodule:
          - core/analyzer.common
          - core/analyzer.js
          - core/analyzer.jvm
          #- core/checker.js
          - core/checker.jvm
          - core/runtime.jvm
          - util/annotator.jvm
          - util/lang.jvm
          - lib/clojure
          - lib/core.async
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Run ${{ matrix.submodule }} tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "${{ matrix.clojure }}"}}}'
        working-directory: ${{ matrix.submodule }}
